spring:
  application:
    name: "shipment-service"

  datasource:
    url: "jdbc:postgresql://pg-2:5432/shipment-service"
    username: postgres
    password: test
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true