#k8s olsun
spring:
    datasource:
      url: "jdbc:postgresql://pg-service:5433/shipment-service"
      username: postgres
      password: test
    jpa:
      showSql: true
      hibernate:
        ddlAuto: update
    cloud:
      stream:
        defaultBinder: kafka
        function:
          definition: shipmentCreatedFunction
        bindings:
          shipmentCreatedFunction-out-0:
            destination: shipment-topic
            content-type: application/json
        kafka:
          binder:
            brokers: localhost
            defaultBrokerPort: 9092
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: "http://eureka-service:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true

