spring:
  datasource:
    url: jdbc:postgresql://pg-2:5432/shipment-service
    username: postgres
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    stream:
      default-binder: kafka
      function:
        definition: shipmentCreatedFunction
      bindings:
        shipmentCreatedFunction-out-0:
          destination: shipment-topic
          content-type: application/json
      kafka:
        binder:
          # 'localhost' yerine docker-compose'daki kafka servis adını yazmalısın
          brokers: kafka:9092
server:
  port: 8083
eureka:
  client:
    service-url:
      # 'eureka' servis adının docker-compose ile eşleştiğinden emin ol
      defaultZone: "http://eureka:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true